### ISSUE TITLE
Web sitesinde Github linki hatalı

### ISSUE THREAD

**Issue by aliemre** [mehmetakifakkus/turkceprogramlamadili#1]
Selam Mehmet,

Web sitesi üzerinde [kaynak kod bölümünde](https://mehmetakifakkus.github.io/turkceprogramlamadili/hakkinda.html#source) Github linki hatalı verilmiş.

**Comment by mehmetakifakkus** [comment]
Uyarınız için teşekkür ederim Ali Emre Bey, en kısa zamanda gidereceğim.
