### ISSUE TITLE
Math Functions on C Translation

### ISSUE THREAD

**Issue by ghost** [mehmetakifakkus/turkceprogramlamadili#3]
When i try to use math functions (like ceil, sqrt, floor, abs) in C file converted by "Türkçe Programlama Dili" conversion system i got error.
The Code i wrote in "Türkçe Programlama Dili"
```
yaz karekök(2)
yaz taban(2)
yaz tavan(2)
yaz mutlak(2)
```

The C code converted by "Türkçe Programlama Dili" conversion system
```c
#include <stdio.h>

int main(){

printf("%f\n", math.sqrt(2));
printf("%d\n", math.floor(2));
printf("%d\n", math.ceil(2));
printf("%d\n", math.abs(2));

return 0;
}
```
And the error threw by C compiler
```c
batuhan@osmantaskaya > /tmp > make init
cc     init.c   -o init
init.c: In function ‘main’:
init.c:5:16: error: ‘math’ undeclared (first use in this function); did you mean ‘main’?
 printf("%f\n", math.sqrt(2));
                ^~~~
                main
init.c:5:16: note: each undeclared identifier is reported only once for each function it appears in
make: *** [<builtin>: init] Error 1
``` 
And it is why it does not work
> “math.h” and “stdlib.h” header files support all the arithmetic functions in C language.  
This code should be like this;
```c
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
int main(){

printf("%f\n", sqrt(2));
printf("%d\n", floor(2));
printf("%d\n", ceil(2));
printf("%d\n", abs(2));

return 0;
}
```
And the output of executed file
```c
 batuhan@osmantaskaya > /tmp > make init  
cc     init.c   -o init
 batuhan@osmantaskaya > /tmp > ./init
1.414214
1679573600
1679573600
2
```

**Comment by mehmetakifakkus** [comment]
Thanks for pointing out the issue. Actually I aware of the problem, and you are the first one who figure it out. I did not want to wait until fixing it.

When i translate it into C version in the function **translate.js**, i directly put the javascript version. Instead i need to put its C version. For each function, i need to put them in a table and put the correct one using that table.

Thanks for informing. 

I like hearing new ideas and discussing them. Also, i will be waiting for them.
