### ISSUE TITLE
Error Mesage Label doesn't fit to the box

### ISSUE THREAD

**Issue by ghost** [mehmetakifakkus/turkceprogramlamadili#4]
![image](https://user-images.githubusercontent.com/25110697/39085583-8c7fd37c-458d-11e8-9ac8-c1a91e12a252.png)
According to source code "Satır 4 hata içeriyor. Lütfen kontrol ed" error message label should be "Satır 4 hata içeriyor. Lütfen kontrol edin." but i dont know why it doesn't fit. Maybe it related with my browser.

Browser: Mozilla Firefox 59.0 - Developer Ed. on GNU/Linux

**Comment by mehmetakifakkus** [comment]
Thank you for your kind advice. We'll take care of it soon.
