### ISSUE TITLE
degisken yerine $ sentaksi

### ISSUE THREAD

**Issue by esokullu** [mehmetakifakkus/turkceprogramlamadili#5]
`Degisken` fazla uzun ve çocuklar icin cok anlam ifade etmeyecek bir kelime. Onun yerine `$` gibi bir sentaks daha mantikli olabilir. Ya da `deger` ifadesi kullanilabilir.

**Comment by mehmetakifakkus** [comment]
Söz dizimi (syntax) için bir kurul olarak karar alıyoruz ve bu önerinizi de göz önünde bulunduracağız. 

Teşekkürler.

**Comment by leventesen** [comment]
`Değişken` kelimesi `sabit ` kelimesi varken daha anlamlı olur diye düşünüyorum. Belki ileride `sabit 
 ` kelimesi de eklenebilir, ileriye dönük açık kapı bırakmak açısından `değişken` olarak kalması daha mantıklı sanki.

`Değer` kelimesine gelirsek, `değer` kelimesi de bir `değişken` yada `sabit`i kapsayabilecek daha genel bir anahtar kelime olarak kullanılabilir.

Çıkış noktası olarak her kelimenin kendi anlamında kullanılması gerektiği gerçeğini baz alıyorum.

Hep beraber güzel birşeyler oluşturacağız sanırsam.

**Comment by mehmetakifakkus** [comment]
Değerli görüşleriniz için teşekkür ederim Emre ve Levent bey, esasında dilimiz herhangi bir keyword olmadan da değişken oluşturmayı sağlıyor. Örneğin: 
```
değişken a = 5 
a = 5
```
Yukarıdaki 1 ve 2 numaralı satırlar aynı işlevi görmekte. Hatta **değ** anahtar kelimesi de İngilizce **var** karşılığı olarak dilin içerisinde mevcut. Yeni başlayan öğrencilerde değişken kavramının oturması amaçlı özellikle pedogojik amaçlı **değişken** kelimesi özellikle kullanılıyor.  Yoksa bu dilin usta bir kullanıcısı **değişken** kelimesini atlayarak kodunu yazabilir. Bazı dillerde "var" kelimesini kullanıp kullanmamak özel bir anlam taşır ki; şu an o bahisten hariçtir.

**Sabit** meselesine gelince programlamaya yeni başlayan kimseler için çok mevzu bahis olmayan bir konu, bizim için de şimdilik öyle. Zamanı gelince tartışalım ama. İsterseniz belirlenme önceliği kritik konulardan biraz bahsedeyim:

1) Dizi tanımı ve eleman erişimi nasıl olmalı? Slicing nasıl olmalı? [ ] karakterler mi yoksa küme parantezi olan { } mı daha uygundur. Dizi indexlemede negatif değerler anlam ifade etmeli mi? Aynı boyuttaki 2 dizi numpy kütüphanesindeki gibi toplanabilmeli mi? (Yani birbirine denk gelen elemanlar). Dil neleri kendi içinde getirmeli varsayılan olarak?

2) Fonksiyon tanımı nasıl olmalı? Static scope mu dynamic scope mu tercih edilmeli? Fonksiyonel dillerin bazı nimetlerini burada kullansak mı? 

3) Struct tarzı bir yapı mı yoksa class yapısını mı benimsemeli? İkisinin de avantajları ve dezavantajları?

gibi giden deli sorular....
